services:
  - type: web
    name: layeredgequiz
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn edgenos.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: edgenos.settings
      - key: PYTHONUNBUFFERED
        value: "1"